[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sok-core"
version = "0.1"
description = "SOK CORE"
dependencies = [
    "sok-api"
]

[tool.setuptools.packages.find]
where = ["src"]