[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "citations-api"
version = "0.1"
description = "Citations API for bibliographic data management."
dependencies = []

[tool.setuptools]
provides = ["citations"]
